In [15]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

In [12]:
# Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its
# application.
Min-max scaling or Normalization is used in data preprocessing. For a dataset that contains features that
vary in magnitudes or units, normalization is used to sacle the units in a range [0,1] or [-1,1]
It is useful where outliers are not present and the distribution is unknown

# Example:
data = pd.DataFrame([123,234,644,12,899],columns=['Number'])
print(data)
    
minmax = MinMaxScaler()
scaled_data = minmax.fit_transform(data)
print(scaled_data)
# Data gets Scaled down to values ranging [0,1]

   Number
0     123
1     234
2     644
3      12
4     899
[[0.12514092]
 [0.25028185]
 [0.71251409]
 [0.        ]
 [1.        ]]


In [16]:
# Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?
# Provide an example to illustrate its application.
Unit vector is used to scale the values of a feature to have a magnitude of 1 while preserving the direction 
of the original data.

Unit Vector Scaling (Normalization):
For each data point in a feature column, you calculate the magnitude of the vector formed by the values of 
that feature across all data points.
Then, divide each value in the feature column by the magnitude obtained in the previous step.
Unit Vector scaling normalizes the data points to have a magnitude of 1, which means they lie on the unit
circle. It preserves the relative direction of data point

Min-Max Scaling:
Min-Max scaling scales the values of a feature to a specific range, typically between 0 and 1.
For each data point in a feature column, you subtract the minimum value of the column from the data point and 
then divide it by the range (the difference between the maximum and minimum values of the column).
Min-Max scaling doesn't guarantee a fixed direction between data points.

# Creating dummy data
data = {'x': [3.0, 1.0, 6.0, 2.0],
        'y': [4.0, 2.0, 8.0, 2.0]}

# Converted data to a dataframe
df = pd.DataFrame(data)
print(df)

# Calculate magnitude
magnitude = np.sqrt(df['x'] ** 2 + df['y'] ** 2)

# Divide each element by the magnitude
df['x_normalized'] = df['x'] / magnitude
df['y_normalized'] = df['y'] / magnitude

print(df[['x_normalized', 'y_normalized']])


     x    y
0  3.0  4.0
1  1.0  2.0
2  6.0  8.0
3  2.0  2.0
   x_normalized  y_normalized
0      0.600000      0.800000
1      0.447214      0.894427
2      0.600000      0.800000
3      0.707107      0.707107


In [18]:
# Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an
# example to illustrate its application.
Principal Component Analysis (PCA) is a dimensionality reduction technique.It transforms a high-dimensional 
dataset into a lower-dimensional one while preserving as much of the variance in the original data as possible.
It is used to address problems such as the curse of dimensionality, reduce noise in data, and improve model
performance by reducing the number of features without losing significant information.


# Sample data (Height and Weight of individuals)
data = np.array([[160, 60], [165, 65], [155, 55], [180, 85], [170, 70]])

# Initialize PCA with one component (to reduce to one dimension)
pca = PCA(n_components=1)

# Fit PCA to the data and transform it to the lower-dimensional space
data_reduced = pca.fit_transform(data)

# data_reduced now contains the data in a one-dimensional space
data_reduced

array([[ -9.21874675],
       [ -2.1762509 ],
       [-16.26124259],
       [ 22.78999529],
       [  4.86624495]])

In [19]:
# Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature
# Extraction? Provide an example to illustrate this concept.
PCA Extracts new features as well as reduce dimensions
PCA can be used for feature extraction: 
Data Transformation: PCA transforms the original data into a new set of features, which are linear combinations 
of the original features. These new features are called principal components.

Ordering by Variance: PCA orders the principal components in descending order of the variance.

Feature Selection: To perform feature extraction, you can select a subset of the top principal components
that collectively explain a high percentage (e.g., 95%) of the total variance in the data.
 
data = np.array([[0.7, 0.8, 0.6],
                 [0.5, 0.7, 0.4],
                 [0.9, 0.6, 0.8],
                 [0.4, 0.5, 0.3],
                 [0.6, 0.7, 0.5]])

# Initialize PCA with two components
pca = PCA(n_components=2)

# Fit PCA to the data and transform it to the lower-dimensional space
data_transformed = pca.fit_transform(data)
data_transformed

array([[ 0.13103331,  0.12341098],
       [-0.16273589,  0.06258618],
       [ 0.38422562, -0.11300741],
       [-0.32990894, -0.11644781],
       [-0.0226141 ,  0.04345805]])

In [ ]:
# Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset
# contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to
# preprocess the data.

data = pd.read_csv('your_dataset.csv')

# Define the features to be scaled
features_to_scale = ['price', 'rating', 'delivery_time']

# Initialize Min-Max scaler
scaler = MinMaxScaler()

# Fit the scaler to your data and transform it
data[features_to_scale] = scaler.fit_transform(data[features_to_scale])

By applying Min-Max scaling, all the features will have a consistent scale, making it easier 
to build a recommendation system that considers different feature values effectively.


In [ ]:
# Q6. You are working on a project to build a model to predict stock prices. The dataset contains many
# features, such as company financial data and market trends. Explain how you would use PCA to reduce the
# dimensionality of the dataset.

The data first needs to be clean. Like there is no missing values, categorical values are encoded, etc
Goal of PCA is to find a smaller set of uncorrelated variables (principal components) that capture most 
of the variance in the original data.
PCA is sensitive to scale of features.So Satndard scaling is used first.

scaler = StandardScaler()
scaled_data = scaler.fit_transform(your_data)

# Apply PCA
pca = PCA(n_components=0.95)  # Retain 95% of the variance
pca_result = pca.fit_transform(scaled_data)

In [23]:
# Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the
# values to a range of -1 to 1.

# Creating pandas Dataframe
data = pd.DataFrame([1, 5, 10, 15, 20],columns=["Number"])

# Initialize scaler Instance with feature_range of -1 to 1
scale = MinMaxScaler(feature_range=(-1, 1))

# Fit and transform the data
scale.fit_transform(data)

array([[-1.        ],
       [-0.57894737],
       [-0.05263158],
       [ 0.47368421],
       [ 1.        ]])

In [ ]:
# Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform
# Feature Extraction using PCA. How many principal components would you choose to retain, and why?
The number of principal components to retain in a PCA-based feature extraction depends on several factors:
1. Variance : choice is to retain enough components to capture a high percentage of the total variance, 
    such as 95% or 99%.
2. Requirements of your analysis or model : To Reduce dimensionality, fewer components can be reatined.
3. Main patterns in the data should be remained to interpret the data